sudo: required
dist: xenial
group: legacy

language: cpp

compiler:
   - gcc
#   - clang

branches:
   except:
      - tmp

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get update -qq
   - sudo apt-get install -qq autotools-dev libkpathsea-dev libfreetype6-dev libgs-dev libz-dev texlive-base python-lxml asciidoc xmlto xsltproc

env:
   global:
      - GTEST_COLOR=1
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      # via the "travis encrypt" command using the project repo's public key
      - secure: "MlOXG2PegI8ck67gSCoY0w4hncbaJ0UG+5VUOmzZ4blJDrA2BLOnQg8n/D65ic1pzmrooUuZJJMmgWI+6F+pyZyXTOpDP50cX4i8WpcuHY/phYp9w2jdN61YgqoUIgWgxsAxBUV2Lf1ULZbWYwUoI9fLkTE6owFXZPFT5ZQnwWA="

addons:
   coverity_scan:
      project:
         name: mgieseki/dvisvgm
         description: "dvisvgm -- A fast DVI to SVG converter"
         version: 2.11
      notification_email: martin.gieseking@uos.de
      build_command_prepend: "./configure --enable-bundled-libs; make clean"
      build_command: "make -j"
      branch_pattern: coverity_scan

script:
   - uname -a
   - ./autogen.sh
   - ./configure --enable-bundled-libs
   - make
   - make -C src -t
   - make check
